# -*- mode: python ; coding: utf-8 -*-

block_cipher = None

a = Analysis(['start_spider.py'],
             pathex=[],
             binaries=[],
             datas=[],
             hiddenimports=['fetcher.heimaofetcher',
                            'fetcher.xueqiufetcher',
                            'pydantic.dataclasses',
                            'pydantic.version',
                            'pydantic.color',
                            'colorsys',
                            'pydantic.types',
                            'pydantic.validators',
                            'pydantic.datetime_parse',
                            'pydantic.main',
                            'pydantic.parse',
                            'pydantic.networks',
                            'pydantic.annotated_types',
                            'pydantic.decorator',
                            'pydantic.env_settings',
                            'pydantic.tools',
                            'uvicorn.loops',
                            'uvicorn.logging',
                            'uvicorn.loops.auto',
                            'uvicorn.protocols',
                            'uvicorn.protocols.http',
                            'uvicorn.protocols.http.auto',
                            'uvicorn.protocols.websockets',
                            'uvicorn.protocols.websockets.auto',
                            'uvicorn.lifespan',
                            'uvicorn.lifespan.on',
                            'anyio._backends',
                            'anyio._backends._asyncio',
                            ],
             hookspath=[],
             hooksconfig={},
             runtime_hooks=[],
             excludes=[],
             win_no_prefer_redirects=False,
             win_private_assemblies=False,
             cipher=block_cipher,
             noarchive=False)
pyz = PYZ(a.pure, a.zipped_data,
          cipher=block_cipher)

exe = EXE(pyz,
          a.scripts,
          a.binaries,
          a.zipfiles,
          a.datas,
          [],
          name='spider',
          debug=False,
          bootloader_ignore_signals=False,
          strip=False,
          upx=True,
          upx_exclude=[],
          runtime_tmpdir=None,
          console=True,
          disable_windowed_traceback=False,
          target_arch=None,
          codesign_identity=None,
          entitlements_file=None)
